-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjSKoBMcobyQ1hcyi
t+ATmfjcq9Wa7gCJFYF50nG+7gigCgYIKoZIzj0DAQehRANCAASh/EYJgFbdZ8Mo
wjZjlec1zAvO0o0The1U+cW4rD5kLxTfyj3waSBWqK7pfMegP/Cp8k+oKmcqopDD
DCNAeqIa
-----END PRIVATE KEY-----